intents:
  - greet
  - user_opportunity_name
  - user_account_name
  - ask_state_name
  - ask_contact_name
  - ask_title_name
  - ask_pricing
  - ask_estimate
  - ask_circuit_type
  - ask_product_type
  - ask_bandwidth
  - ask_location_A_a
  - ask_location_Z_z
  - ask_submit_opp
  - ask_submit_cir

entities:
   - opportunity_name
   - account_name
   - state_name
   - contact_name
   - title_name
   - pricing
   - estimate_type
   - circuit_type
   - product_type
   - bandwidth
   - location_Z_z
   - location_A_a

slots:
   opportunity_name:
       type: text
   state_name:
       type: text
   account_name:
       type: text
   contact_name:
       type: text
   title_name:
       type: text
   pricing:
       type: text
   estimate_type:
       type: text
   circuit_type:
       type: text
   product_type:
       type: text
   bandwidth:
       type: text 
   location_A_a:
       type: text
   location_Z_z:
       type: text


actions:
     - action_default_fallback
     - utter_greet
     - utter_opportunity_name
     - utter_opportunity_type
     - utter_opportunity_done
     - utter_account_name
     - utter_state_list
     - utter_contact
     - utter_title
     - utter_pricing
     - utter_estimate
     - utter_circuit
     - utter_product
     - utter_bandwidth
     - utter_location_A_a
     - utter_location_Z_z
     - utter_submit_circuit
     - utter_submit_option
     - action_submit_cir
     - utter_submit_opp
     


templates:
  utter_greet:
    - text: "Hi! This is Tom,  UPN’s virtual assistant."
  utter_opportunity_name:
    - text: "To create an opportunity mention the opportunity name."

  utter_account_name:
    - text: " Please mention the account name."
  utter_opportunity_done:
    - text: ' An opportunity named "{opportunity_name}" has been created with account name "{account_name}" .'
  utter_opportunity_type:
    - text: " Opportunity type : New Business"




  utter_title:
     - text: "To add an option for this opportunity, please mention title name."
       


  utter_state_list:
    - text: 'Select the state from state list.'
      buttons:
      - title: "AZ"
        payload: '/ask_state_name{"state_name":"AZ"}'
      - title: "CA"
        payload: '/ask_state_name{"state_name":"CA"}'
      - title: "CO"
        payload: '/ask_state_name{"state_name":"CO"}'
      

  utter_contact:
    - text: "Choose the primary contact name from the given list."
      buttons:
      - title: "Jason Miller"
        payload: '/ask_contact_name{"contact_name":"Jason Miller"}'
      - title: "Jerome Simoneau"
        payload: '/ask_contact_name{"contact_name":"Jerome Simoneau"}'
      - title: "Tom Felton"
        payload: '/ask_contact_name{"contact_name":"Tom Felton"}'
      - title: "Joseph Fiennes"
        payload: '/ask_contact_name{"contact_name":"Joseph Fiennes"}'
      - title: "Colin Firth"
        payload: '/ask_contact_name{"contact_name":"Colin Firth"}'
      - title: "Emilia Fox "
        payload: '/ask_contact_name{"contact_name":"Emilia Fox"}'

  
  utter_pricing:
     - text: "Choose the type of pricing from the list."
       buttons:
       - title: "On Net"
         payload: '/ask_pricing{"pricing":"On Net"}'
       - title: "ICB"
         payload: '/ask_pricing{"pricing":"ICB"}'
       - title: "Near Net"
         payload: '/ask_pricing{"pricing":"Near Net"}'


  utter_estimate:
     - text: "Choose the estimate type from the given list."
       buttons:
       - title: "$0 - $50K (3 Days-RVP Approval)"
         payload: '/ask_estimate{"estimate_type":"$0 - $50K (3 Days-RVP Approval)"}'
       - title: "$51K - $150K (4 Days-RVP Approval)"
         payload: '/ask_estimate{"estimate_type":"$51K - $150K (4 Days-RVP Approval)"}'
       - title: "$151K - $500K (6 Days-RVP & VP Const Approval)"
         payload: '/ask_estimate{"estimate_type":"$151K - $500K (6 Days-RVP & VP Const Approval)"}'
       - title: "$501K - $1.5M (10 Days-RVP, VP Const & COO)"
         payload: '/ask_estimate{"estimate_type":"$501K - $1.5M (10 Days-RVP, VP Const & COO)"}'
       - title: "New Markets (15 Days-RVP, VP Const & COO)"
         payload: '/ask_estimate{"estimate_type":"New Markets (15 Days-RVP, VP Const & COO)"}'

  utter_submit_opp:
     - text: "Click below to submit the option for this opportunity."
       buttons:
       - title: "Submit"
         payload: '/ask_submit_opp'



  utter_submit_option:
     - text: "An option for this opportunity has been submitted."

  utter_circuit:
     - text: "To add the circuit choose the circuit type."
       buttons:
       - title: "New Circuit"	
         payload: '/ask_circuit_type{"circuit_type":"New Circuit"}'
       

  utter_product:
     - text: "Choose the product type."
       buttons:
       - title: "Bidirectional NNI"	
         payload: '/ask_product_type{"product_type":"Bidirectional NNI"}'
       - title: "Cloud Connect"
         payload: '/ask_product_type{"product_type":"Cloud Connect"}'
       - title: "Colo Service"
         payload: '/ask_product_type{"product_type":"Colo Service"}'
       - title: "Cross Connect"
         payload: '/ask_product_type{"product_type":"Cross Connect"}'
  
  
  utter_bandwidth:
     - text: "Tell me the bandwidth value."



  utter_location_A_a:
    - text: "Select an appropriate location in Location A circuit."
      buttons:
      - title: "123 E Marcy St Ste 201, Santa Fe, NM, 87501, Santa Fe Office (Modrall Sperling)"
        payload: '/ask_location_A_a{"location_A_a":"123 E Marcy St Ste 201, Santa Fe, NM, 87501, Santa Fe Office (Modrall Sperling)"}'
      - title: "115 N Second Ave E, Newton, IA, 50208, Jasper County Annex"
        payload: '/ask_location_A_a{"location_A_a":"115 N Second Ave E, Newton, IA, 50208, Jasper County Annex"}'
       

  utter_location_Z_z:
    - text: "Select an appropriate location in Location Z circuit."
      buttons:
        - title: "123 E Marcy St Ste 201, Santa Fe, NM, 87501, Santa Fe Office (Modrall Sperling)"
          payload: '/ask_location_Z_z{"location_Z_z":"123 E Marcy St Ste 201, Santa Fe, NM, 87501, Santa Fe Office (Modrall Sperling)"}'
        - title: "115 N Second Ave E, Newton, IA, 50208, Jasper County Annex"
          payload: '/ask_location_Z_z{"location_Z_z":"115 N Second Ave E, Newton, IA, 50208, Jasper County Annex"}'
  utter_submit_circuit:
    - text: "Click below to save the circuit."
      buttons:
        - title: "Save Circuit"
          payload: '/ask_submit_cir'
   
  







